version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: central-sms-user
      POSTGRES_PASSWORD: UkK99iNftvlYJdWIBLOp38lHFEXjmJ
      POSTGRES_DB: central-sms-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
